name: interest_book
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences: ^2.2.3
  another_flutter_splash_screen: ^1.2.1
  video_player: ^2.5.2
  lottie: ^3.0.0
  http: ^1.2.0
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.6
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.0.12
  provider: ^6.0.5
  image_picker: ^0.8.4+4
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  intl: ^0.18.0
  pdf: ^3.10.7
  printing: ^5.12.0

flutter:
  uses-material-design: true
  assets:
  - assest/
